### ISSUE TITLE
Run Migrations Step Not Working

### ISSUE THREAD

**Issue by anthony-cervantes** [cabotapp/docker-cabot#1]
I am getting the following error when attempting to deploy cabot via docker-compose via the steps in the README

```
user01@cabot01:/opt/docker-cabot# docker-compose run --rm web python /manage.py migrate
python: can't open file '/manage.py': [Errno 2] No such file or directory
```

**Comment by dbuxton** [comment]
Looks like there's a typo in the readme, shouldn't be an absolute path

    docker-compose run --rm web python manage.py migrate

should work...

**Comment by anthony-cervantes** [comment]
still the same issue.
```
user01@cabot01:/opt/docker-cabot# docker-compose run --rm web python manage.py migrate
Creating dockercabot_rabbitmq_1
Creating dockercabot_postgres_1
python: can't open file 'manage.py': [Errno 2] No such file or directory
```

**Comment by anthony-cervantes** [comment]
when I run a simple `ls` I don't see any manage.py

```
user01@cabot01:/opt/docker-cabot# docker-compose run --rm web ls
bin      etc      lib      media    proc     run      srv      tmp      var
dev      home     linuxrc  mnt      root     sbin     sys      usr
```

**Comment by dbuxton** [comment]
Right you are @anthony-cervantes - I will let @frankh deal with this when he has a second. Looks like README needs some fixes, thanks for pointing out.

**Comment by frankh** [comment]
@anthony-cervantes sorry about this, the readme is out of date

There is now a `cabot` executable, and the command to migrate is `cabot migrate`

**Comment by anthony-cervantes** [comment]
Thanks! that cleared up my issue!
