### ISSUE TITLE
 Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by asaf050** [cabotapp/docker-cabot#13]
Hello,
I'm not familiar with Docker, but try to install Cabot with it as a quick start...

I set up new VPS on ubuntu 16.04 , Docker 1.12.6, docker-compose 1.8.0.
When starting with ` docker-compose up -d` I get the following error:
`Version in "./docker-compose.yml" is unsupported.`

Any ideas?

Thanks

**Comment by dbuxton** [comment]
You need docker-compose ≥ 1.9.0: https://docs.docker.com/compose/compose-file/compose-versioning/
