### ISSUE TITLE
README.md and .env is out-of-date wrt docker images

### ISSUE THREAD

**Issue by patrickdepinguin** [cabotapp/docker-cabot#14]
The README contains a list of supported tags, but this is out-of-date: it lists 0.10.8 as latest, while 0.11.9 is already there. This is very confusing, both on the github repo as on the Docker Hub.

Similarly, the .env file that specifies the image to use, still specifies 0.11.2. 

I suggest to either update the README every time a new image is pushed, or (perhaps easier) just leave out those descriptions and let users use the standard mechanisms, like the 'Tags' tab on Docker Hub or the 'Releases' tag in GitHub on the main cabot repo.

For the .env file I suggest to update it every time a new image is pushed.

**Comment by frankh** [comment]
They should all be up to date now
