### ISSUE TITLE
Unable to get a meaningful response from web server

### ISSUE THREAD

**Issue by Bouncey** [cabotapp/docker-cabot#17]
When-ever I `curl` the web server on `http://127.0.0.1:5000`, I only get a 302 response. Trying to access from a web browser I get a 522 (through cloudfront). I have nuked everything, even down to changing droplets but I can't get past this issue.

I have tried it behind my own nginx proxy, the Caddy proxy you provide, I have even opened up port 80 directly to the app but I never receive the index page.

Any help would be greatly appreciated

**Comment by dbuxton** [comment]
Pinging `127.0.0.1` sounds wrong to me - look at the IP of the docker host itself?
