### ISSUE TITLE
Where can I find the production.env config after launching with docker-compose

### ISSUE THREAD

**Issue by bpr-sulli** [cabotapp/docker-cabot#18]
Hi,

I set up Cabot successfully with the docker-compose configuration, but now I've no idea where to find the production.env or conf folder. Can anyone tell me which container this now lives in so I can configure Slack and other plugins?

Thanks,

**Comment by dbuxton** [comment]
docker-compose reads the conf and makes variables available in the environment directly: https://github.com/arachnys/cabot/blob/a9dc61cd39df9b7c7ac55ae13cd1a2a38c3d47df/docker-compose.yml#L8

Does that answer your question? 

If you're running in production you'll want to be doing something like `docker run -d --name cabot-web --env-file production.env --link cabot-postgres:postgres --link cabot-redis:redis -p 5000:5000 cabotapp/cabot gunicorn cabot.wsgi:application -b 0.0.0.0:5000` (see https://github.com/cabotapp/docker-cabot)
