### ISSUE TITLE
InfluxDB support

### ISSUE THREAD

**Issue by kishuagarwal** [cabotapp/docker-cabot#19]
I plan to use influxdb for metrics collection. Any suggestions on how to use this with cabot?

**Comment by dbuxton** [comment]
Cabot now supports check plugins: http://cabotapp.com/dev/writing-check-plugins.html to augment the default stack of checks.

Documentation is pretty non-existent but if you wanted to do something along these lines, the community would, I'm sure, find it useful.

**Comment by JeanFred** [comment]
Original enhancement request is at https://github.com/arachnys/cabot/issues/151

**Comment by dbuxton** [comment]
Thanks @JeanFred - I'll close this in favour of #151

**Comment by kishuagarwal** [comment]
@JeanFred  Thanks for pointing to the other issue.

Also when we add the plugin in CABOT_PLUGINS_ENABLED, is that sufficient or do we also have to modify the django templates as well to insert the <li> item for the new check?
