### ISSUE TITLE
Version mismatch is on Docker-Compose up

### ISSUE THREAD

**Issue by aaronpederson** [cabotapp/docker-cabot#23]
`git clone git@github.com:cabotapp/docker-cabot.git`
(https://cabotapp.com/qs/quickstart.html)

`docker-compose -f docker-compose.yml -f docker-compose-caddy.yml up -d`
_ERROR: Version mismatch: file ./docker-compose.yml specifies version 2.0 but extension file ./docker-compose-caddy.yml uses version 2.1
ERROR: Version mismatch: file ./docker-compose.yml specifies version 2.1 but extension file .../docker-cabot/docker-compose-base.yml uses version 2.0_

**Comment by frankh** [comment]
fixed, thanks for the PR
