### ISSUE TITLE
documentation on third party plugin installation

### ISSUE THREAD

**Issue by anthony-cervantes** [cabotapp/docker-cabot#4]
Can we get documentation on the best generic way to install third party plugins via pip and enabling via the `<environment>.conf`?

**Comment by frankh** [comment]
hi @anthony-cervantes 

This is still in the pipeline. For now the best way is probably to create your own Dockerfile to add the plugins and update the docker-compose to use that

```Dockerfile
FROM cabotapp/cabot:<version>

RUN pip install <plugin>
```
