### ISSUE TITLE
SSL/TLS email sending needs dependencies

### ISSUE THREAD

**Issue by skylerbunny** [cabotapp/docker-cabot#5]
I'm not sure whether this is a problem best solved at the docker-cabot level, or pushed upstream to cabot to put into requirements, but:

If the OS docker-cabot is installed and does NOT have the package python-openssl (ubuntu), py-openssl (alpine), etc. installed, attempting to send mail using the default production.env configuration file produces the error:

```
SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:661)
ERROR 2017-04-27 22:37:07,686 exception 26 139787706329896 Internal Server Error: /alert-test-plugin/
```

This is because, in a nutshell, the python library pyopenssl is not available to the dockercabot_web container. I can fix this by doing one of two things.

1. I include `py-openssl` in the Dockerfile.build `apk add` section. This satisfies the dependency inside the container. Now I'll get the more friendly error amounting to 'I can do SSL but the other side isn't speaking it.'
```
error: [Errno 104] Connection reset by peer
ERROR 2017-04-27 22:41:25,852 exception 35 140337258289960 Internal Server Error: /alert-test-plugin/
```
2. I do nothing inside the docker-cabot environment, but DO install pyopenssl in the encapsulating system's python libraries (or in the virtualenv in which I'm working, which is equivalent for these purposes).

If (1) is the answer, this is a docker-cabot bug and this dependency should be included in Dockerfile.build. If (2) is the preferred answer, this is a cabot bug in general and a dependency is missing for a fully functional application.

It occurs to me this may even be a dependency that should be included in BOTH places.

**Comment by dbuxton** [comment]
One thing I think @JeanFred was thinking about was how to manage dependencies of alert plugins. I seem to remember you mentioning Sentry as an example. Can you suggest a good solution to this?

**Comment by skylerbunny** [comment]
I've not had discussions about cabot here before (this is the first day I've contacted cabotapp/arachnys with issue reports).

That being said, since plugins are defined as versioned requirements here, https://github.com/arachnys/cabot/blob/master/requirements-plugins.txt, one could in turn make pyopenssl a requirement of https://github.com/arachnys/cabot-alert-email . Currently it has no child dependencies at all, and one might argue it should since it presumes to use SSL features.

**Comment by frankh** [comment]
I've just tested this and it works on cabot 0.11.7.

If you're still having issues please re-open with the specific email options you're using.
